# Generated by Django 2.2.4 on 2020-09-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_auto_20200923_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='shoes_bought',
            field=models.ManyToManyField(related_name='bought_by', to='ecommerce_app.Shoe'),
        ),
    ]
