# Generated by Django 2.2.4 on 2020-09-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_auto_20200923_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shoes_liked',
            field=models.ManyToManyField(related_name='liked_by', to='ecommerce_app.Shoe'),
        ),
    ]
