# Generated by Django 2.2.4 on 2020-09-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0005_shoe_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='img',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
