# Generated by Django 2.2.4 on 2020-09-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0007_shoe_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
